<?php

namespace AppBundle\Repository;

/**
 * ProducersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducersRepository extends \Doctrine\ORM\EntityRepository
{
}
